server:
  port: 7777
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: route1
          predicates:
            - Path=/account/**
          filters:
            - RewritePath=/account/(?<s>.*), /${s}
          uri: http://localhost:8000/
        - id: route2
          predicates:
            - Path=/posts/**
          filters:
            - RewritePath=/posts/(?<s>.*), /${s}
          uri: http://localhost:8001/
        - id: route3
          predicates:
            - Path=/reservations/**
          filters:
            - RewritePath=/reservations/(?<s>.*), /${s}
          uri: http://localhost:8002/
