server:
  port: 7777

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8888/eureka
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: route1
          predicates:
            - Path=/account/**
          filters:
            - RewritePath=/account/(?<s>.*), /${s}

          uri: http://localhost:8000/
        - id: route1
          predicates:
            - Path=/posts/**
          filters:
            - RewritePath=/posts/(?<s>.*), /${s}

          uri: http://localhost:8001/
